### ISSUE TITLE
1장 리뷰

### ISSUE THREAD

**Issue by Joie-Kim** [Joie-Kim/effective_ts#2]
## Note
- [1장 : 타입스크립트 알아보기](https://www.notion.so/huijooooo/1-1643fdb1fa1a445f814c340451e713e8)

## QnA
- p24 예시 이해 안 됨... (설명해줄 사람?)
- 타입스크립트가 유닛 테스트 할 때 좋다는데, 왜 ?? 이유가 뭐지 ?? 예시 봐도 이해 안 됨..
>- 유닛 테스트 코드를 안 짜봐서 그런가봄 ㅠㅠ ...

**Comment by HyeonJiKwon** [comment]
### QnA
1. 번역이 이상한 거 같..
2. 다른 사람이 짠 코드를 테스트 하려고 하는데, 구조 설계가 되어있으면 더 용이함!
>- 왜냐면 구조를 다 알고 있기 때문이다. 하하
